# Generated by Django 3.0.1 on 2020-02-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meteorite',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rec_class', models.CharField(max_length=50)),
                ('mass', models.FloatField()),
                ('fall', models.CharField(max_length=20)),
                ('year', models.DateTimeField()),
                ('rec_latitude', models.CharField(max_length=200)),
                ('rec_longitude', models.CharField(max_length=200)),
                ('geolocation', models.CharField(max_length=250)),
            ],
        ),
    ]
