# Generated by Django 3.0.1 on 2020-02-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meteorite',
            old_name='mass',
            new_name='mass_in_kg',
        ),
    ]
