# Generated by Django 3.0.1 on 2020-02-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20200203_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meteorite',
            old_name='mass_in_kg',
            new_name='mass',
        ),
    ]
