# Generated by Django 3.0.1 on 2020-02-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20200203_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteorite',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
